name: Check Internal Markdown Links

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  internal-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Check internal Markdown links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: >-
            --offline
            --include-fragments
            --root-dir .
            --verbose
            --no-progress
            "**/*.md"
          fail: true
          failIfEmpty: true
          format: markdown
          jobSummary: true
          lycheeVersion: v0.23.0
          output: lychee/internal-links.md
